# Generated by Django 5.2 on 2025-04-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=150, verbose_name='название продукта')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('product_launch_date', models.DateTimeField(verbose_name='дата выхода на рынок')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.entrepreneur')),
            ],
            options={
                'verbose_name': 'продукт индивидуального предпринимателя',
                'verbose_name_plural': 'продукты индивидуальных предпринимателей',
            },
        ),
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=150, verbose_name='название продукта')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('product_launch_date', models.DateTimeField(verbose_name='дата выхода на рынок')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.factory')),
            ],
            options={
                'verbose_name': 'продукт завода',
                'verbose_name_plural': 'продукты завода',
            },
        ),
        migrations.CreateModel(
            name='NetworkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=150, verbose_name='название продукта')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('product_launch_date', models.DateTimeField(verbose_name='дата выхода на рынок')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.network')),
            ],
            options={
                'verbose_name': 'продукт розничной сети',
                'verbose_name_plural': 'продукты розничных сетей',
            },
        ),
    ]
